services:
  WebClient:
    image: nginx:latest
    container_name: WebClient
    ports:
      - "8000:8000"
    volumes:
      - ./front/web/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./front/web/:/usr/share/nginx/html